# Site settings
title: MVBC
email: kirk@mvbc.co.za
description: "Montana Vikings Basketball Club"

# Live site settings - uncomment for live push
# baseurl: "http://www.mvbc.co.za"
# url: "http://www.mvbc.co.za"

# Testing site settings - uncomment for local dev
baseurl: ""
url: ""

permalink: /:categories/:title
version: 1.0

# Build settings
markdown: kramdown
permalink: pretty

exclude: [README.md, Gruntfile.js, package.json, 'node_modules', '*.esproj']

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"